name: compare-revisions
version: 0.1.0
synopsis: Show how sets of images differ, by revision
description: Please see README.md
maintainer: Jonathan M. Lange <jml@weave.works>
license: Apache
github: jml/compare-revisions
category: Web

ghc-options: -Wall -Werror
default-extensions:
  - NoImplicitPrelude
  - OverloadedStrings
  - RecordWildCards

dependencies:
  - base >= 4.9 && < 5
  - protolude

library:
  source-dirs: src
  dependencies:
    - aeson
    - array
    - attoparsec
    - bytestring
    - containers
    - directory
    - exceptions
    - filepath
    - fsnotify
    - http-media
    - http-types
    - logging
    - lucid
    - mtl
    - network-uri
    - optparse-applicative
    - process
    - prometheus-client
    - prometheus-metrics-ghc
    - regex-tdfa
    - QuickCheck
    - servant
    - servant-server
    - stm
    - text
    - time
    - unix
    - unordered-containers
    - yaml
    - wai
    - wai-extra
    - wai-middleware-prometheus
    - warp

executables:
  compare-revisions:
    main: Main.hs
    ghc-options: -threaded
    source-dirs: cmd
    dependencies:
      - compare-revisions

  compare-images:
    main: CompareImages.hs
    source-dirs: cmd
    dependencies:
      - compare-revisions
      - containers
      - optparse-applicative

tests:
  tasty:
    main: Main.hs
    source-dirs: tests
    dependencies:
      - compare-revisions
      - hspec
      - QuickCheck
      - tasty
      - tasty-hspec
      - text
      - yaml
