# Update CircleCI config when you change this.
resolver: lts-11.1

packages:
  - .

extra-deps:
  - logging-3.0.4

image:
  containers:
    - base: "ubuntu:18.04"
      name: "quay.io/weaveworks/compare-revisions"
      executables:
        - compare-revisions
      entrypoints:
        # This will generate an image called:
        # `quay.io/weaveworks/compare-revisions-compare-revisions`
        - compare-revisions
