name: compare-revisions-server
version: 0.1.0
synopsis: Show how sets of images differ, by revision
description: Please see README.md
maintainer: Jonathan M. Lange <jml@weave.works>
license: Apache
github: jml/compare-revisions
category: Web

ghc-options: -Wall -Werror
default-extensions:
  - NoImplicitPrelude
  - OverloadedStrings
  - RecordWildCards

dependencies:
  - base >= 4.9 && < 5
  - protolude

library:
  source-dirs: src
  dependencies:
    - compare-revisions-api
    - aeson
    - bytestring
    - containers
    - directory
    - exceptions
    - filepath
    - http-media
    - http-types
    - logging-effect
    - mtl
    - optparse-applicative
    - process
    - prometheus-client
    - prometheus-metrics-ghc
    - servant-server
    - text
    - time
    - unix
    - unordered-containers
    - yaml
    - wai
    - wai-extra
    - wai-middleware-prometheus
    - warp
    - wl-pprint-text

executables:
  compare-revisions:
    main: Main.hs
    source-dirs: cmd
    dependencies:
      - compare-revisions-server

  compare-images:
    main: CompareImages.hs
    source-dirs: cmd
    dependencies:
      - compare-revisions-server
      - containers
      - optparse-applicative

tests:
  compare-revisions-server-tests:
    main: Main.hs
    source-dirs: tests
    dependencies:
      - compare-revisions-api
      - compare-revisions-server
      - logging-effect
      - QuickCheck
      - servant-quickcheck
      - tasty
      - tasty-hspec
