name: compare-revisions-api
version: 0.1.0
synopsis: Show how sets of images differ, by revision
description: Please see README.md
maintainer: Jonathan M. Lange <jml@weave.works>
license: Apache
github: jml/compare-revisions
category: Web

ghc-options: -Wall -Werror
default-extensions:
  - NoImplicitPrelude
  - OverloadedStrings
  - RecordWildCards

dependencies:
  - base >= 4.9 && < 5
  - protolude

library:
  source-dirs: src
  dependencies:
    - aeson
    - http-media
    - neat-interpolation
    - servant

tests:
  compare-revisions-api-tests:
    main: Main.hs
    source-dirs: tests
    dependencies:
      - compare-revisions-api
      - tasty
